version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
       - java -version
       - docker -v

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/
  build:
    commands:
      - ./gradlew bootjar
      - BOOT_JAR=`ls build/libs/*.jar`
      - echo $BOOT_JAR
      - echo Building the Layered Docker Image with Gradlew
      - ./gradlew clean bootBuildImage | tee ./tmp
      - TEST=$(./tmp)
      - DOCKER_IMAGE_NAME=$(grep 'Building image' ./tmp | awk '{print $3}' | tr -d "'")
      - DOCKER_IMAGE_TAG=$(echo $DOCKER_IMAGE_NAME | awk -F ':' '{print $2}')
      - echo .....$TEST
      - echo .....$DOCKER_IMAGE_NAME
      - echo .....$DOCKER_IMAGE_TAG
# Building image 'docker.io/library/shop:0.0.1-SNAPSHOT'
      - docker tag $DOCKER_IMAGE_NAME $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$IMAGE_REPO_NAME:$DOCKER_IMAGE_TAG
      - docker tag $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$IMAGE_REPO_NAME:$DOCKER_IMAGE_TAG $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$IMAGE_REPO_NAME:latest
      - docker push --all-tags $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$IMAGE_REPO_NAME


  post_build:
    commands:
      - DATE='date'
      - echo Build completed on $DATE

