server:
  port: 8080
spring:
  application:
    name: springboot-shop-test
  jpa:
    #    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    #    hibernate:
    #      ddl-auto: update
    #      naming:
    #        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    #    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc-secretsmanager:mysql://${DB_ENDPOINT}:3306/shop
    username: test/shop/mysql-8.x
    driver-class-name: com.amazonaws.secretsmanager.sql.AWSSecretsManagerMySQLDriver

#  datasource:
#    url: jdbc:mysql://localhost:3306/shop
#    username: shop
#    password: shop
#    driver-class-name: com.mysql.cj.jdbc.Driver


logging.level.root : info

